#pragma config(Sensor, S4,     touchSensorL,    sensorEV3_Touch)
#pragma config(Sensor, S1,     touchSensorR,    sensorEV3_Touch)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)

void turnRight();
void turnLeft();
void backUp();
void travelLeft();
void travelRight();
void travelForward();
void sharpRight();
void sharpLeft();
task detectSensor();
task moveRandomly();
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task detectSensor() {
		int i = 0;
		bool back = false;
		while(true) {
				if (SensorValue[touchSensorR]) {
						while(i++ < 200) { //check for 300 ms (bar still isn't very sensitive)
							if(SensorValue[touchSensorL]) {
								back = true;
								i = 200;
								break;
							}
							wait1Msec(1);
						}
	  				stopTask(moveRandomly);
						stopAllMotors();
						if (back) {
							backUp();
						} else {
							turnLeft();
							travelLeft();
						}
						back = false;
						i = 0;
						startTask(moveRandomly);
				}
				if (SensorValue[touchSensorL]) {
						while (i++ < 200) {
							if (SensorValue[touchSensorR]){
								back = true;
								i = 200;
								break;
							}
							wait1Msec(1);
						}
						stopTask(moveRandomly);
						stopAllMotors();
						if (back) {
							backUp();
						} else {
							turnRight();
							travelRight();
						}
						back = false;
						i = 0;
						startTask(moveRandomly);
				}
				sleep(15);
		}
}

task moveRandomly
{

	int randomMove = random(10);
	int direc = random(1); //left or right
	while (true) {

		if (direc++ % 2 == 0) {
			travelRight();
				//randomMove = random(10);
		}else {
			travelLeft();
		}
	}
}

task main() {
	startTask(moveRandomly);
	startTask(detectSensor);
	while(true) {
		wait(300);
	}
}


/**
 * backs up for 2 seconds, then turns right at a random angle
 */
void turnRight() {
	displayCenteredBigTextLine(4, "Back");
	setLEDColor(ledOff);
	setMotor(motorC, -50);
	setMotor(motorB, -50);
	sleep(2000);
	sharpRight();
	/*setMotor(motorC, 10);
	setMotor(motorB, random(100));
	sleep(random(3000) + 500); //3 seconds good?
	*/
}

/**
 * backs up for 2 seconds, then turns left at a random angle
 */
void turnLeft() {
	displayCenteredBigTextLine(4, "Back");
	setLEDColor(ledOff);
	setMotor(motorB, -50);
	setMotor(motorC, -50);
	sleep(2000);
	sharpLeft();
	/*setMotor(motorB, 10);
	setMotor(motorC, random(80) + 20);
	sleep(random(3000) + 500);*/
}

/**
 * backs up, goes left or right randomely at a random angle
 */
void backUp() {
	playTone(400, 20);
	displayCenteredBigTextLine(4, "Back");
	setLEDColor(ledOff);
	setMotor(motorB, -50);
	setMotor(motorC, -50);
	sleep(2000);
	stopAllMotors();
	sleep(2000);
	if (random(1)) //0 or 1, true or false... maybe?
	{
		sharpRight();
	}
	else {
		sharpLeft();
	}
	sleep(random(1500) + 500);
}

void travelRight() {
	displayCenteredBigTextLine(4, "Right");
	setLEDColor(ledGreen);
	int rightT = random(30) + 30; //30-60
	//int leftT = random(25) + 20; //20-45
	double leftPercentage = ((random(3) + 6) * 0.1); //0.60-0.90 of the main speed
	int leftT = leftPercentage * rightT;
	setMotor(motorB, leftT);
	setMotor(motorC, rightT);
	sleep(random(600) + 1100); //Heavy turn = light duration and vice versa
}

void travelLeft() {
	displayCenteredBigTextLine(4, "Left");
	setLEDColor(ledRed);
	int leftT = random(30) + 30;
	double rightPercentage = ((random(3) + 6) * 0.1);
	int rightT = rightPercentage * leftT;
	setMotor(motorB, leftT);
	setMotor(motorC, rightT);
	sleep(random(600) + 1100);
}
/*Just make some progress mostly straight
* Might be useful but use in moderation
*/
void travelForward() {
	displayCenteredBigTextLine(4, "Straight");
	setLEDColor(ledOff);
	setMotor(motorB, 50 + random(10));
	setMotor(motorC, 50 + random(10));
	sleep(random(500) + 1000);
}

//Should turn about 90 degrees left
void sharpLeft() {
	displayCenteredBigTextLine(4, "Left");
	setLEDColor(ledRed);
	setMotor(motorB, 50);
	setMotor(motorC, 0);
	sleep(200);
}

void sharpRight() {
	displayCenteredBigTextLine(4, "Right");
	setLEDColor(ledGreen);
	setMotor(motorB, 0);
	setMotor(motorC, 50);
	sleep(200);
}
