#pragma config(Sensor, S4,     touchSensorL,    sensorEV3_Touch)
#pragma config(Sensor, S1,     touchSensorR,    sensorEV3_Touch)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)

void turnRight();
void turnLeft();
void backUp();
void travelLeft();
void travelRight();
void travelForward();
void sharpRight();
void sharpLeft();
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*task detectSensor() {
	while(true) {
		if (SensorValue[touchSensorL] && SensorValue[touchSensorR]) {
		} else if (!SensorValue[touchSensorL] && SensorValue[touchSensorR]) {
		} else if (SensorValue[touchSensorL] && !SensorValue[touchSensorR]) {
		}
	}
}

task moveRandomly() {

}*/

task main()
{
	/*
	int R = random(100);
	int L = random(100);

	while(true){
		R = random(40);
		L = random(40);
		setMotor(motorC, L);
		setMotor(motorB, R);
		//wait(2500, milliseconds);
		//stopAllMotors();
		if (SensorValue[touchSensorL] && SensorValue[touchSensorR])
		{
			playTone(400, 20);
			backUp();
		}
		else if (!SensorValue[touchSensorL] && SensorValue[touchSensorR])
		{
			turnRight();
		}
		else if (SensorValue[touchSensorL] && !SensorValue[touchSensorR])
		{
			turnLeft();
		}
		sleep(random(1000) + 100);
	}
*/



	int randomMove = random(5);
	while (true) {
		if (SensorValue[touchSensorL] && SensorValue[touchSensorR]) {
				playTone(400, 20);
				backUp();
	  } else if (!SensorValue[touchSensorL] && SensorValue[touchSensorR]) {
				turnRight();
			} else if (SensorValue[touchSensorL] && !SensorValue[touchSensorR]) {
				turnLeft();
			} else if (randomMove == 0) {
				travelRight();
				randomMove = random(5);
	  	} else if (randomMove == 1) {
	  		travelLeft();
	  		randomMove = random(5);
		  } else if (randomMove == 2) {
		 		sharpRight();
		 		randomMove = random(5);
			} else if (randomMove == 3) {
				sharpLeft();
				randomMove = random(5);
			} else {
				travelForward();
				randomMove = random(5);
			}
	 }
}


/**
 * backs up for 2 seconds, then turns right at a random angle
 */
void turnRight() {
	setMotor(motorC, -50);
	setMotor(motorB, -50);
	sleep(2000);
	sharpRight();
	/*setMotor(motorC, 10);
	setMotor(motorB, random(100));
	sleep(random(3000) + 500); //3 seconds good?
	*/
}

/**
 * backs up for 2 seconds, then turns left at a random angle
 */
void turnLeft() {
	setMotor(motorB, -50);
	setMotor(motorC, -50);
	sleep(2000);
	sharpLeft();
	/*setMotor(motorB, 10);
	setMotor(motorC, random(80) + 20);
	sleep(random(3000) + 500);*/
}

/**
 * backs up, goes left or right randomely at a random angle
 */
void backUp() {
	setMotor(motorB, -50);
	setMotor(motorC, -50);
	sleep(2000);
	if (random(1)) //0 or 1, true or false... maybe?
	{
		setMotor(motorB, 10);
		setMotor(motorC, random(80) + 20);
	}
	else {
		setMotor(motorC, 10);
		setMotor(motorB, random(100));
	}
	sleep(random(3000) + 500);
}

void travelLeft() {
	setMotor(motorB, 50);
	setMotor(motorC, 60);
	sleep(random(3000) + 500);
}

void travelRight() {
	setMotor(motorB, 60);
	setMotor(motorC, 50);
	sleep(random(3000) + 500);
}

void travelForward() {
	setMotor(motorB, 60);
	setMotor(motorC, 60);
	sleep(random(2000) + 500);
}

void sharpRight() {
	setMotor(motorB, 50);
	setMotor(motorC, 0);
	sleep(400);
}

void sharpLeft() {
	setMotor(motorB, 0);
	setMotor(motorC, 50);
	sleep(400);
}
