#pragma config(Sensor, S1,     touchSensorL,    sensorEV3_Touch)
#pragma config(Sensor, S4,     touchSensorR,    sensorEV3_Touch)
#pragma config(Motor,  motorR,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorL,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	int R = random(100);
	int L = random(100);

	while(true){
		R = random(40);
		L = random(40);
		setMotor(motorL, L);
		setMotor(motorR, R);
		//wait(2500, milliseconds);
		//stopAllMotors();
		if (SensorValue[touchSensorL] && SensorValue[touchSensorR])
		{
			playTone(400, 20);
			backup();
		}
		else if (!SensorValue[touchSensorL] && SensorValue[touchSensorR])
		{
			turnRight();
		}
		else if if (SensorValue[touchSensorL] && !SensorValue[touchSensorR])
		{
			turnLeft();
		}
		sleep(random(100));
	}
	
	

}

/**
 * backs up for 2 seconds, then turns right at a random angle
 */
void turnRight() {
	setMotor(motorL, -50);
	setMotor(motorR, -50);
	sleep(2000);
	setMotor(motorL, 10);
	setMotor(motorR, random(100));
	sleep(random(3000)); //3 seconds good?
}

/**
 * backs up for 2 seconds, then turns left at a random angle
 */
int turnLeft() {
	setMotor(motorR, -50);
	setMotor(motorL, -50);
	sleep(2000);
	setMotor(motorR, 10);
	setMotor(motorL, random(100));
	sleep(random(3000));
}

/**
 * backs up, goes left or right randomely at a random angle
 */
int backUp() {
	setMotor(motorR, -50);
	setMotor(motorL, -50);
	sleep(2000)
	if (random(1)) //0 or 1, true or false... maybe?
	{
		setMotor(motorR, 10);
		setMotor(motorL, random(100));
	}
	else {
		setMotor(motorL, 10);
		setMotor(motorR, random(100));
	}
	sleep(random(3000));
}

	
	